version: "3.3"
services:
  traefik:
    image: "traefik:v2.3"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  web:
    build: '.'
    image: 'brounder'
    environment:
      DJANGO_PASSWORD: 'pass'
      REDIS_MASTER_SERVICE_HOST: 'redis'
      POSTGRES_SERVICE_HOST: 'postgres'
    # ports:
    #   - '8000:80'
    command: bash -c "python manage.py migrate && gunicorn brounder.wsgi:application -w 2 -b :80"
    volumes:
      - 'cachedata:/cache'
      - 'mediadata:/media'
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
volumes:
  pgdata:
  redisdata:
  cachedata:
  mediadata: